version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

homebrew_casks:
  - name: leggo
    binaries:
      - leggo
    repository:
      owner: andresrobam
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_SCOOP_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/andresrobam/leggo"
    description: "A command line background process orchestrator"

scoops:
  - name: leggo
    repository:
      owner: andresrobam
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW_SCOOP_TOKEN }}"
    homepage: "https://github.com/andresrobam/leggo"
    description: "A command line background process orchestrator"
